package com.example.e_library

import android.os.Build
import android.os.Bundle
import android.util.Log
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.activity.viewModels
import androidx.annotation.RequiresApi
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.platform.LocalContext
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import com.example.e_library.data.AuthViewModel
import com.example.e_library.data.NetworkViewModel
import com.example.e_library.navigation.AppNavHost
import com.example.e_library.navigation.ROUTE_ABOUT_SCREEN_ADMIN
import com.example.e_library.navigation.ROUTE_ABOUT_SCREEN_CLIENT
import com.example.e_library.navigation.ROUTE_ABOUT_SCREEN_DELIVERY_PERSONNEL
import com.example.e_library.navigation.ROUTE_ABOUT_SCREEN_GUEST
import com.example.e_library.navigation.ROUTE_ABOUT_SCREEN_STAFF
import com.example.e_library.navigation.ROUTE_ADD_BOOKS
import com.example.e_library.navigation.ROUTE_ADD_CART
import com.example.e_library.navigation.ROUTE_ADMIN_CLIENT_EDIT
import com.example.e_library.navigation.ROUTE_ADMIN_DELIVERY_PERSONNEL_EDIT
import com.example.e_library.navigation.ROUTE_ADMIN_EDIT_ACCOUNT
import com.example.e_library.navigation.ROUTE_ADMIN_EDIT_HOME
import com.example.e_library.navigation.ROUTE_ADMIN_FEEDBACK
import com.example.e_library.navigation.ROUTE_ADMIN_LOGIN
import com.example.e_library.navigation.ROUTE_ADMIN_REGISTER
import com.example.e_library.navigation.ROUTE_ADMIN_STAFF_EDIT
import com.example.e_library.navigation.ROUTE_ADMIN_VIEW_ACCOUNT
import com.example.e_library.navigation.ROUTE_BOOKS_HOME
import com.example.e_library.navigation.ROUTE_BORROW_BOOKS_CLIENT
import com.example.e_library.navigation.ROUTE_BORROW_BOOKS_STAFF
import com.example.e_library.navigation.ROUTE_BORROW_HOME
import com.example.e_library.navigation.ROUTE_CLIENT_FEEDBACK
import com.example.e_library.navigation.ROUTE_CLIENT_HOME
import com.example.e_library.navigation.ROUTE_CLIENT_LOGIN
import com.example.e_library.navigation.ROUTE_CLIENT_REGISTER
import com.example.e_library.navigation.ROUTE_CLIENT_VIEW_MY_DELIVERY
import com.example.e_library.navigation.ROUTE_CONTACT_US
import com.example.e_library.navigation.ROUTE_COURIER_VIEW_CLIENT_DELIVERY
import com.example.e_library.navigation.ROUTE_DASHBOARD
import com.example.e_library.navigation.ROUTE_DELIVERY_DETAILS
import com.example.e_library.navigation.ROUTE_DELIVERY_PERSONNEL_CONTACT_AS_ADMIN
import com.example.e_library.navigation.ROUTE_DELIVERY_PERSONNEL_CONTACT_AS_CLIENT
import com.example.e_library.navigation.ROUTE_DELIVERY_PERSONNEL_CONTACT_AS_DELIVERY_PERSONNEL
import com.example.e_library.navigation.ROUTE_DELIVERY_PERSONNEL_CONTACT_AS_STAFF
import com.example.e_library.navigation.ROUTE_DELIVERY_PERSONNEL_FEEDBACK
import com.example.e_library.navigation.ROUTE_DELIVERY_PERSONNEL_HOME
import com.example.e_library.navigation.ROUTE_DELIVERY_PERSONNEL_LOGIN
import com.example.e_library.navigation.ROUTE_DELIVERY_PERSONNEL_REGISTER
import com.example.e_library.navigation.ROUTE_EDIT_BOOKS
import com.example.e_library.navigation.ROUTE_EDIT_CLIENT_INFO
import com.example.e_library.navigation.ROUTE_EDIT_DELIVERY_PERSONNEL_ACCOUNT
import com.example.e_library.navigation.ROUTE_EDIT_STAFF_INFO
import com.example.e_library.navigation.ROUTE_EULA_ADMIN
import com.example.e_library.navigation.ROUTE_EULA_CLIENT
import com.example.e_library.navigation.ROUTE_EULA_DELIVERY_PERSONNEL
import com.example.e_library.navigation.ROUTE_EULA_GUEST
import com.example.e_library.navigation.ROUTE_EULA_STAFF
import com.example.e_library.navigation.ROUTE_HOME
import com.example.e_library.navigation.ROUTE_PRIVACY_POLICY_ADMIN
import com.example.e_library.navigation.ROUTE_PRIVACY_POLICY_CLIENT
import com.example.e_library.navigation.ROUTE_PRIVACY_POLICY_DELIVERY_PERSONNEL
import com.example.e_library.navigation.ROUTE_PRIVACY_POLICY_GUEST
import com.example.e_library.navigation.ROUTE_PRIVACY_POLICY_STAFF
import com.example.e_library.navigation.ROUTE_RETURN_BOOKS
import com.example.e_library.navigation.ROUTE_SPLASH
import com.example.e_library.navigation.ROUTE_STAFF_CONTACT_AS_ADMIN
import com.example.e_library.navigation.ROUTE_STAFF_CONTACT_AS_CLIENT
import com.example.e_library.navigation.ROUTE_STAFF_CONTACT_AS_DELIVERY_PERSONNEL
import com.example.e_library.navigation.ROUTE_STAFF_CONTACT_AS_STAFF
import com.example.e_library.navigation.ROUTE_STAFF_FEEDBACK
import com.example.e_library.navigation.ROUTE_STAFF_HOME
import com.example.e_library.navigation.ROUTE_STAFF_LOGIN
import com.example.e_library.navigation.ROUTE_STAFF_REGISTER
import com.example.e_library.navigation.ROUTE_USER_MANUAL_ADMIN
import com.example.e_library.navigation.ROUTE_USER_MANUAL_CLIENT
import com.example.e_library.navigation.ROUTE_USER_MANUAL_DELIVERY_PERSONNEL
import com.example.e_library.navigation.ROUTE_USER_MANUAL_GUEST
import com.example.e_library.navigation.ROUTE_USER_MANUAL_STAFF
import com.example.e_library.navigation.ROUTE_VIEW_ALL_BOOKS
import com.example.e_library.navigation.ROUTE_VIEW_ALL_BOOKS_CLIENT
import com.example.e_library.navigation.ROUTE_VIEW_BOOKS
import com.example.e_library.navigation.ROUTE_VIEW_BOOKS_GUEST
import com.example.e_library.navigation.ROUTE_VIEW_CART_CLIENT
import com.example.e_library.navigation.ROUTE_VIEW_CART_CLIENTS_DELIVERY_PERSONNEL
import com.example.e_library.navigation.ROUTE_VIEW_CART_ITEMS_FOR_CLIENT
import com.example.e_library.navigation.ROUTE_VIEW_CLIENTS
import com.example.e_library.navigation.ROUTE_VIEW_CLIENT_BORROWS
import com.example.e_library.navigation.ROUTE_VIEW_CLIENT_INFO
import com.example.e_library.navigation.ROUTE_VIEW_DELIVERY_PERSONNEL_ACCOUNT
import com.example.e_library.navigation.ROUTE_VIEW_STAFF_BORROWS
import com.example.e_library.navigation.ROUTE_VIEW_STAFF_INFO
import com.example.e_library.ui.theme.ELibraryTheme
import com.example.e_library.ui.theme.screens.about.AboutScreenAdmin
import com.example.e_library.ui.theme.screens.about.AboutScreenClient
import com.example.e_library.ui.theme.screens.about.AboutScreenDeliveryPersonnel
import com.example.e_library.ui.theme.screens.about.AboutScreenGuest
import com.example.e_library.ui.theme.screens.about.AboutScreenStaff
import com.example.e_library.ui.theme.screens.admin.AdminClientEdit
import com.example.e_library.ui.theme.screens.admin.AdminDeliveryPersonnelEdit
import com.example.e_library.ui.theme.screens.admin.AdminEditAccount
import com.example.e_library.ui.theme.screens.admin.AdminEditHome
import com.example.e_library.ui.theme.screens.admin.AdminLogInScreen
import com.example.e_library.ui.theme.screens.admin.AdminRegisterScreen
import com.example.e_library.ui.theme.screens.admin.AdminStaffEdit
import com.example.e_library.ui.theme.screens.admin.AdminViewAccount
import com.example.e_library.ui.theme.screens.books.AddBooksScreen
import com.example.e_library.ui.theme.screens.books.BooksHomeScreen
import com.example.e_library.ui.theme.screens.books.EditBooksScreen
import com.example.e_library.ui.theme.screens.books.ViewAllBooksScreen
import com.example.e_library.ui.theme.screens.books.ViewBooksScreen
import com.example.e_library.ui.theme.screens.borrowing.BorrowBooksClientScreen
import com.example.e_library.ui.theme.screens.borrowing.BorrowBooksStaffScreen
import com.example.e_library.ui.theme.screens.borrowing.BorrowHomeScreen
import com.example.e_library.ui.theme.screens.borrowing.ViewClientBorrowedBooks
import com.example.e_library.ui.theme.screens.borrowing.ViewStaffBorrowedBooks
import com.example.e_library.ui.theme.screens.borrowing.ViewClientsScreen
import com.example.e_library.ui.theme.screens.cart.AddCartScreen
import com.example.e_library.ui.theme.screens.delivery.DeliveryDetails
import com.example.e_library.ui.theme.screens.cart.ViewBooksAddedToCart
import com.example.e_library.ui.theme.screens.cart.ViewCartClientsDeliveryPersonnel
import com.example.e_library.ui.theme.screens.cart.ViewCartItemsForClient
import com.example.e_library.ui.theme.screens.clients.ClientHomeScreen
import com.example.e_library.ui.theme.screens.clients.ClientLogInScreen
import com.example.e_library.ui.theme.screens.clients.ClientRegisterScreen
import com.example.e_library.ui.theme.screens.clients.EditClientInfo
import com.example.e_library.ui.theme.screens.clients.ViewAllBooksClient
import com.example.e_library.ui.theme.screens.clients.ViewClientInfo
import com.example.e_library.ui.theme.screens.contact.ContactDeliveryPersonnelAsAdmin
import com.example.e_library.ui.theme.screens.contact.ContactDeliveryPersonnelAsClient
import com.example.e_library.ui.theme.screens.contact.ContactDeliveryPersonnelAsDeliveryPersonnel
import com.example.e_library.ui.theme.screens.contact.ContactDeliveryPersonnelAsStaff
import com.example.e_library.ui.theme.screens.contact.ContactStaffAsAdmin
import com.example.e_library.ui.theme.screens.contact.ContactStaffAsClient
import com.example.e_library.ui.theme.screens.contact.ContactStaffAsDeliveryPersonnel
import com.example.e_library.ui.theme.screens.contact.ContactStaffAsStaff
import com.example.e_library.ui.theme.screens.contact.ContactUsScreen
import com.example.e_library.ui.theme.screens.dashboard.DashboardScreen
import com.example.e_library.ui.theme.screens.delivery.ClientViewMyDelivery
import com.example.e_library.ui.theme.screens.delivery.CourierViewClientDelivery
import com.example.e_library.ui.theme.screens.deliveryPersonnel.DeliveryPersonnelEditAccount
import com.example.e_library.ui.theme.screens.deliveryPersonnel.DeliveryPersonnelHome
import com.example.e_library.ui.theme.screens.deliveryPersonnel.DeliveryPersonnelLoginScreen
import com.example.e_library.ui.theme.screens.deliveryPersonnel.DeliveryPersonnelRegisterScreen
import com.example.e_library.ui.theme.screens.deliveryPersonnel.DeliveryPersonnelViewAccount
import com.example.e_library.ui.theme.screens.endUserLicenceAgreement.EndUserLicenceAgreementScreenAdmin
import com.example.e_library.ui.theme.screens.endUserLicenceAgreement.EndUserLicenceAgreementScreenClient
import com.example.e_library.ui.theme.screens.endUserLicenceAgreement.EndUserLicenceAgreementScreenDeliveryPersonnel
import com.example.e_library.ui.theme.screens.endUserLicenceAgreement.EndUserLicenceAgreementScreenGuest
import com.example.e_library.ui.theme.screens.endUserLicenceAgreement.EndUserLicenceAgreementScreenStaff
import com.example.e_library.ui.theme.screens.feedback.FeedbackScreenAdmin
import com.example.e_library.ui.theme.screens.feedback.FeedbackScreenClient
import com.example.e_library.ui.theme.screens.feedback.FeedbackScreenDeliveryPersonnel
import com.example.e_library.ui.theme.screens.feedback.FeedbackScreenStaff
import com.example.e_library.ui.theme.screens.home.HomeScreen
import com.example.e_library.ui.theme.screens.home.ViewBooksGuest
import com.example.e_library.ui.theme.screens.privacyPolicy.PrivacyPolicyScreenAdmin
import com.example.e_library.ui.theme.screens.privacyPolicy.PrivacyPolicyScreenClient
import com.example.e_library.ui.theme.screens.privacyPolicy.PrivacyPolicyScreenDeliveryPersonnel
import com.example.e_library.ui.theme.screens.privacyPolicy.PrivacyPolicyScreenGuest
import com.example.e_library.ui.theme.screens.privacyPolicy.PrivacyPolicyScreenStaff
import com.example.e_library.ui.theme.screens.returning.ReturnBooksScreen
import com.example.e_library.ui.theme.screens.splash.SplashScreen
import com.example.e_library.ui.theme.screens.staff.EditStaffInfo
import com.example.e_library.ui.theme.screens.staff.StaffHomeScreen
import com.example.e_library.ui.theme.screens.staff.StaffLogInScreen
import com.example.e_library.ui.theme.screens.staff.StaffRegisterScreen
import com.example.e_library.ui.theme.screens.staff.ViewStaffInfo
import com.example.e_library.ui.theme.screens.userManual.UserManualScreenAdmin
import com.example.e_library.ui.theme.screens.userManual.UserManualScreenClient
import com.example.e_library.ui.theme.screens.userManual.UserManualScreenDeliveryPersonnel
import com.example.e_library.ui.theme.screens.userManual.UserManualScreenGuest
import com.example.e_library.ui.theme.screens.userManual.UserManualScreenStaff

class MainActivity : ComponentActivity() {
    @RequiresApi(Build.VERSION_CODES.O)
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            ELibraryTheme {
                AppNavHost()
            }
        }
    }
}